In [1]:
import pandas as pd

In [12]:
df_rna = pd.read_csv('../data/res/rna_deg/DEG-normalized.csv', sep=',')
df_rna['gene'] = df_rna['gene'].str.split(':').str[1]
df_rna.head(2)

,Unnamed: 0,gene,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,C1.counts.txt,C2.counts.txt,C3.counts.txt,C4.counts.txt,T1.counts.txt,T2.counts.txt,T3.counts.txt,T4.counts.txt
0,1,TraesCS2B02G286300,320.013057,2.445059,0.225052,10.864392,1.703534e-27,5.369907e-23,582.257421,553.695714,476.353565,549.686360,77.245985,81.333777,93.617622,145.914014
1,2,TraesCS2B02G336800,2294.525203,-2.909846,0.268059,-10.855254,1.882824e-27,5.369907e-23,532.840739,512.938938,500.171243,609.940442,4976.988116,5270.112921,2148.061490,3805.147731

In [5]:
df_mart_traes = pd.read_csv('../data/data/marts/mart_export_traes.txt', sep='\t')
df_mart_traes.head()

,Gene stable ID,GO term accession,GO term name,GO term definition,GO domain,Gene description
0,TraesCS4A02G403700,NaN,NaN,NaN,NaN,NaN
1,TraesCS3A02G154800,GO:0047617,acyl-CoA hydrolase activity,Catalysis of the reaction: acyl-CoA + H2O = Co...,molecular_function,NaN
2,TraesCS2B02G516800,GO:0004553,"hydrolase activity, hydrolyzing O-glycosyl com...",Catalysis of the hydrolysis of any O-glycosyl ...,molecular_function,NaN
3,TraesCS2B02G516800,GO:0005975,carbohydrate metabolic process,The chemical reactions and pathways involving ...,biological_process,NaN
4,TraesCS2B02G516800,GO:0016787,hydrolase activity,"Catalysis of the hydrolysis of various bonds, ...",molecular_function,NaN

In [6]:
df_mart_traes_at = pd.read_csv('../data/data/marts/mart_export_traes_at.txt', sep='\t')
df_mart_traes_at.head()

,Gene stable ID,Arabidopsis thaliana gene stable ID,Arabidopsis thaliana gene name
0,TraesCS4A02G403700,NaN,NaN
1,TraesCS3A02G154800,NaN,NaN
2,TraesCS2B02G516800,AT3G13790,CWINV1
3,TraesCS2B02G516800,AT3G13784,CWINV5
4,TraesCS2B02G516800,AT1G55120,CWINV3

In [7]:
df_mart_at = pd.read_csv('../data/data/marts/mart_export_at.txt', sep='\t')
df_mart_at.head()

,Gene stable ID,GO term accession,GO term name,GO term definition,GO domain,Gene description
0,AT3G11415,NaN,NaN,NaN,NaN,NaN
1,AT1G31258,NaN,NaN,NaN,NaN,other RNA [Source:TAIR;Acc:AT1G31258]
2,AT5G24735,NaN,NaN,NaN,NaN,other RNA [Source:TAIR;Acc:AT5G24735]
3,AT2G45780,NaN,NaN,NaN,NaN,other RNA [Source:TAIR;Acc:AT2G45780]
4,AT2G42425,NaN,NaN,NaN,NaN,Unknown gene [Source:TAIR;Acc:AT2G42425]

In [9]:
df_traes_link_at = pd.merge(df_mart_traes, df_mart_traes_at, on='Gene stable ID', how='left')
df_traes_link_at.head(4)

,Gene stable ID,GO term accession,GO term name,GO term definition,GO domain,Gene description,Arabidopsis thaliana gene stable ID,Arabidopsis thaliana gene name
0,TraesCS4A02G403700,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TraesCS3A02G154800,GO:0047617,acyl-CoA hydrolase activity,Catalysis of the reaction: acyl-CoA + H2O = Co...,molecular_function,NaN,NaN,NaN
2,TraesCS2B02G516800,GO:0004553,"hydrolase activity, hydrolyzing O-glycosyl com...",Catalysis of the hydrolysis of any O-glycosyl ...,molecular_function,NaN,AT3G13790,CWINV1
3,TraesCS2B02G516800,GO:0004553,"hydrolase activity, hydrolyzing O-glycosyl com...",Catalysis of the hydrolysis of any O-glycosyl ...,molecular_function,NaN,AT3G13784,CWINV5

In [10]:
df_traes_at = pd.merge(df_traes_link_at, df_mart_at, left_on='Arabidopsis thaliana gene stable ID', right_on='Gene stable ID', how='left')
df_traes_at.head()

,Gene stable ID_x,GO term accession_x,GO term name_x,GO term definition_x,GO domain_x,Gene description_x,Arabidopsis thaliana gene stable ID,Arabidopsis thaliana gene name,Gene stable ID_y,GO term accession_y,GO term name_y,GO term definition_y,GO domain_y,Gene description_y
0,TraesCS4A02G403700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TraesCS3A02G154800,GO:0047617,acyl-CoA hydrolase activity,Catalysis of the reaction: acyl-CoA + H2O = Co...,molecular_function,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TraesCS2B02G516800,GO:0004553,"hydrolase activity, hydrolyzing O-glycosyl com...",Catalysis of the hydrolysis of any O-glycosyl ...,molecular_function,NaN,AT3G13790,CWINV1,AT3G13790,GO:0016787,hydrolase activity,"Catalysis of the hydrolysis of various bonds, ...",molecular_function,"Beta-fructofuranosidase, insoluble isoenzyme C..."
3,TraesCS2B02G516800,GO:0004553,"hydrolase activity, hydrolyzing O-glycosyl com...",Catalysis of the hydrolysis of any O-glycosyl ...,molecular_function,NaN,AT3G13790,CWINV1,AT3G13790,GO:0005975,carbohydrate metabolic process,The chemical reactions and pathways involving ...,biological_process,"Beta-fructofuranosidase, insoluble isoenzyme C..."
4,TraesCS2B02G516800,GO:0004553,"hydrolase activity, hydrolyzing O-glycosyl com...",Catalysis of the hydrolysis of any O-glycosyl ...,molecular_function,NaN,AT3G13790,CWINV1,AT3G13790,GO:0016798,"hydrolase activity, acting on glycosyl bonds",Catalysis of the hydrolysis of any glycosyl bo...,molecular_function,"Beta-fructofuranosidase, insoluble isoenzyme C..."

In [14]:
df_res_mart = pd.merge(df_rna, df_traes_at, left_on='gene', right_on='Gene stable ID_x', how='left')
df_res_mart.head()

,Unnamed: 0,gene,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,C1.counts.txt,C2.counts.txt,...,GO domain_x,Gene description_x,Arabidopsis thaliana gene stable ID,Arabidopsis thaliana gene name,Gene stable ID_y,GO term accession_y,GO term name_y,GO term definition_y,GO domain_y,Gene description_y
0,1,TraesCS2B02G286300,320.013057,2.445059,0.225052,10.864392,1.703534e-27,5.369907e-23,582.257421,553.695714,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,TraesCS2B02G336800,2294.525203,-2.909846,0.268059,-10.855254,1.882824e-27,5.369907e-23,532.840739,512.938938,...,biological_process,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,TraesCS6D02G241200,191.594697,2.320181,0.223227,10.393825,2.645258e-25,5.029605e-21,300.797192,294.244042,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,TraesCS7B02G073900,681.317343,2.012952,0.195772,10.282137,8.482575e-25,1.209636e-20,1254.753999,895.655005,...,cellular_component,WAT1-related protein [Source:UniProtKB/TrEMBL;...,AT4G08290,NaN,AT4G08290,GO:0080144,amino acid homeostasis,Any process involved in the maintenance of an ...,biological_process,WAT1-related protein At4g08290 [Source:UniProt...
4,4,TraesCS7B02G073900,681.317343,2.012952,0.195772,10.282137,8.482575e-25,1.209636e-20,1254.753999,895.655005,...,cellular_component,WAT1-related protein [Source:UniProtKB/TrEMBL;...,AT4G08290,NaN,AT4G08290,GO:0032973,amino acid export across plasma membrane,The directed movement of amino acids from insi...,biological_process,WAT1-related protein At4g08290 [Source:UniProt...

In [16]:
df_res_mart.to_csv('../data/res/rna_deg/DEG-normalized.mart.csv', sep='\t', index=None)