In [76]:
import pandas as pd

In [77]:
path_target = '../../data/res/04_02_19/psRNATargetJob-1552408016123276.txt'
path_mirnas = '../../data/res/04_02_19/DEG.Y.csv'
path_deg_mir = '../../data/res/04_02_19/diffexpr-results.0.1.csv'
path_deg_genes  = '../../data/res/04_02_19/DEG-normalized.csv'
path_merged = '../../data/res/04_02_19/targets_go.csv'
path_targets_out = '../../data/res/04_02_19/targets.csv'
path_taes = '../../data/GO/taes.csv'
path_taes_2 = '../../data/GO/taes1.0.TAB'
path_aet = '../../data/GO/aet.csv'
path_ath = '../../data/GO/ath.csv'

In [78]:
df_target = pd.read_csv(path_target, sep='\t', comment='#')
print(len(df_target.index))
df_target.rename(columns={'miRNA_Acc.':'miRNA_name','Target_Acc.':'target'}, inplace=True)
df_target = df_target[['miRNA_name','target','Expectation','miRNA_aligned_fragment','Target_aligned_fragment','Inhibition']]
df_target.head(3)

715

,miRNA_name,target,Expectation,miRNA_aligned_fragment,Target_aligned_fragment,Inhibition
0,Cluster_30749,TraesCS5B02G062100.1,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage
1,Cluster_9839,TraesCS2B02G490400.1,2.5,AGGCGGUUACCUUGGCUAGC,GCUGGCCAAGGUGGCCGCCG,Cleavage
2,Cluster_10532,TraesCS7A02G231200.1,3.0,UGGACGAGGAUGUGCAGCUGC,GCAGCUGCAGAUCCUCGUCGA,Cleavage

In [79]:
#create target gene column in df_psrna
df_target['gene'] = df_target['target'].str.split('.').str[0]
df_target.head(2)

,miRNA_name,target,Expectation,miRNA_aligned_fragment,Target_aligned_fragment,Inhibition,gene
0,Cluster_30749,TraesCS5B02G062100.1,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,TraesCS5B02G062100
1,Cluster_9839,TraesCS2B02G490400.1,2.5,AGGCGGUUACCUUGGCUAGC,GCUGGCCAAGGUGGCCGCCG,Cleavage,TraesCS2B02G490400

## add l2fc miRNA

In [80]:
df_deg_mirna = pd.read_csv(path_deg_mir)

In [81]:
df_deg_mirna = df_deg_mirna[['Gene','log2FoldChange']]

In [82]:
df_deg_mirna.head(2)

            Gene  log2FoldChange
0   Cluster_9839       -1.373090
1  Cluster_10532        0.747036

In [83]:
#merge df
df_merged_mirna = pd.merge(df_target, df_deg_mirna, left_on='miRNA_name', right_on='Gene', how='left')
print(len(df_merged_mirna.index))

715

In [84]:
df_merged_mirna.rename(columns={'log2FoldChange':'miRNA_l2fc'}, inplace=True)
df_merged_mirna.drop('Gene', axis=1, inplace=True)

In [85]:
df_merged_mirna.head(3)

,miRNA_name,target,Expectation,miRNA_aligned_fragment,Target_aligned_fragment,Inhibition,gene,miRNA_l2fc
0,Cluster_30749,TraesCS5B02G062100.1,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,TraesCS5B02G062100,0.604528
1,Cluster_9839,TraesCS2B02G490400.1,2.5,AGGCGGUUACCUUGGCUAGC,GCUGGCCAAGGUGGCCGCCG,Cleavage,TraesCS2B02G490400,-1.373090
2,Cluster_10532,TraesCS7A02G231200.1,3.0,UGGACGAGGAUGUGCAGCUGC,GCAGCUGCAGAUCCUCGUCGA,Cleavage,TraesCS7A02G231200,0.747036

## add l2fc gene

In [86]:
df_deg_genes = pd.read_csv(path_deg_genes)

In [87]:
df_deg_genes = df_deg_genes[['gene','log2FoldChange']]
df_deg_genes['gene'] = df_deg_genes['gene'].str.split(':').str[1]

In [88]:
df_deg_genes.head(2)

                 gene  log2FoldChange
0  TraesCS2B02G286300       -2.445058
1  TraesCS2B02G336800        2.909847

In [89]:
#merge df
df_merged_mirna_gene = pd.merge(df_merged_mirna, df_deg_genes, left_on='gene', right_on='gene', how='left')
print(len(df_merged_mirna_gene.index))

715

In [90]:
df_merged_mirna_gene.rename(columns={'log2FoldChange':'gene_l2fc'}, inplace=True)

In [91]:
df_merged_mirna_gene.head(3)

,miRNA_name,target,Expectation,miRNA_aligned_fragment,Target_aligned_fragment,Inhibition,gene,miRNA_l2fc,gene_l2fc
0,Cluster_30749,TraesCS5B02G062100.1,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,TraesCS5B02G062100,0.604528,1.378806
1,Cluster_9839,TraesCS2B02G490400.1,2.5,AGGCGGUUACCUUGGCUAGC,GCUGGCCAAGGUGGCCGCCG,Cleavage,TraesCS2B02G490400,-1.373090,1.957450
2,Cluster_10532,TraesCS7A02G231200.1,3.0,UGGACGAGGAUGUGCAGCUGC,GCAGCUGCAGAUCCUCGUCGA,Cleavage,TraesCS7A02G231200,0.747036,-1.495536

In [92]:
cols = ['miRNA_name','miRNA_l2fc','target','gene','gene_l2fc','Expectation','miRNA_aligned_fragment','Target_aligned_fragment','Inhibition']
df_merged_mirna_gene = df_merged_mirna_gene[cols]

In [93]:
df_merged_mirna_gene.head(2)

,miRNA_name,miRNA_l2fc,target,gene,gene_l2fc,Expectation,miRNA_aligned_fragment,Target_aligned_fragment,Inhibition
0,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage
1,Cluster_9839,-1.373090,TraesCS2B02G490400.1,TraesCS2B02G490400,1.957450,2.5,AGGCGGUUACCUUGGCUAGC,GCUGGCCAAGGUGGCCGCCG,Cleavage

## add miRNA mature sequence

In [94]:
df_mirnas = pd.read_csv(path_mirnas, sep='\t')
df_mirnas = df_mirnas[['Name','MajorRNA','#Locus']]
df_mirnas.head(2)

           Name               MajorRNA                  #Locus
0  Cluster_6291  UGCCAAAGGAGAGUUGCCCUG  2A:652328872-652329011
1  Cluster_6500  UGGACGAGGAUGUGCAGCUGC  2A:707747484-707747579

In [95]:
df = pd.merge(df_merged_mirna_gene,df_mirnas, left_on='miRNA_name',right_on='Name',how='left' )
df.drop('Name', axis=1, inplace=True)

In [96]:
df.head(3)

,miRNA_name,miRNA_l2fc,target,gene,gene_l2fc,Expectation,miRNA_aligned_fragment,Target_aligned_fragment,Inhibition,MajorRNA,#Locus
0,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,GCGGCUCUGUGGUGUUCAAGC,6D:95858420-95858704
1,Cluster_9839,-1.373090,TraesCS2B02G490400.1,TraesCS2B02G490400,1.957450,2.5,AGGCGGUUACCUUGGCUAGC,GCUGGCCAAGGUGGCCGCCG,Cleavage,AGGCGGUUACCUUGGCUAGC,2D:360310978-360311149
2,Cluster_10532,0.747036,TraesCS7A02G231200.1,TraesCS7A02G231200,-1.495536,3.0,UGGACGAGGAUGUGCAGCUGC,GCAGCUGCAGAUCCUCGUCGA,Cleavage,UGGACGAGGAUGUGCAGCUGC,2D:568229232-568229332

In [97]:
len(df_merged_mirna_gene.index)

715

## add GO terms

### triticum

In [98]:
df_taes = pd.read_csv(path_taes_2,sep='\t')
df_taes = df_taes[['Gene-ID','Human-Readable-Description']]
df_taes.rename(columns={'Gene-ID':'gene','Human-Readable-Description':'description'}, inplace=True)
df_taes.head(5)

                   gene                                        description
0  TraesCS1A01G000100.1         tRNA (cytidine(34)-2'-O)-methyltransferase
1  TraesCS1A01G000200.1  Latent-transforming growth factor beta-binding...
2  TraesCS1A01G000300.1              Coiled-coil domain-containing protein
3  TraesCS1A01G000400.1                           ATP synthase gamma chain
4  TraesCS1A01G000500.1  Polyketide cyclase/dehydrase and lipid transpo...

In [99]:
df_taes[df_taes.gene == 'TraesCS6B01G248300.1']

                        gene                            description
106234  TraesCS6B01G248300.1  Bidirectional sugar transporter SWEET

In [100]:
df_taes['gene'] = df_taes['gene'].str.replace('A01','A02')
df_taes['gene'] = df_taes['gene'].str.replace('B01','B02')
df_taes['gene'] = df_taes['gene'].str.replace('D01','D02')

In [101]:
df_taes.head(2)

                   gene                                        description
0  TraesCS1A02G000100.1         tRNA (cytidine(34)-2'-O)-methyltransferase
1  TraesCS1A02G000200.1  Latent-transforming growth factor beta-binding...

In [102]:
df_taes[df_taes.gene == 'TraesCS6B02G248300.1']

                        gene                            description
106234  TraesCS6B02G248300.1  Bidirectional sugar transporter SWEET

In [103]:
df_merged_mirna_gene_taes = pd.merge(df_merged_mirna_gene,df_taes,left_on='target',right_on='gene',how='left')
df_merged_mirna_gene_taes.rename(columns={'gene_x':'gene'}, inplace=True)
df_merged_mirna_gene_taes.drop('gene_y', axis=1, inplace=True)
df_merged_mirna_gene_taes.head()

,miRNA_name,miRNA_l2fc,target,gene,gene_l2fc,Expectation,miRNA_aligned_fragment,Target_aligned_fragment,Inhibition,description
0,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,"Kinase interacting (KIP1-like) family protein,..."
1,Cluster_9839,-1.373090,TraesCS2B02G490400.1,TraesCS2B02G490400,1.957450,2.5,AGGCGGUUACCUUGGCUAGC,GCUGGCCAAGGUGGCCGCCG,Cleavage,Pectinesterase inhibitor domain containing pro...
2,Cluster_10532,0.747036,TraesCS7A02G231200.1,TraesCS7A02G231200,-1.495536,3.0,UGGACGAGGAUGUGCAGCUGC,GCAGCUGCAGAUCCUCGUCGA,Cleavage,Phosphate transporter PHO1-like protein
3,Cluster_10532,0.747036,TraesCS1D02G086000.1,TraesCS1D02G086000,4.589141,3.0,UGGACGAGGAUGUGCAGCUGC,CGAGUUCCACAACCUCGUCCA,Translation,Abnormal spindle-like microcephaly-associated ...
4,Cluster_17678,-1.089684,TraesCS5B02G431600.1,TraesCS5B02G431600,1.339536,3.0,UGGGCAAGUCACCCUGGCUACC,GUCGGCCACGGCGACUUGCCCA,Translation,"Glucan endo-1,3-beta-glucosidase, putative"

In [104]:
df_merged_mirna_gene_taes.to_csv(path_merged,index=None)

In [105]:
path_merged

'../../data/res/04_02_19/targets_go.csv'

In [27]:
df_taes = pd.read_csv(path_taes,sep='\t')
df_taes = df_taes[['Gene stable ID','GO term definition']]
df_taes.rename(columns={'GO term name':'GO_term_triticum','GO term definition':'GO_triticum'}, inplace=True)
df_taes.head(5)

       Gene stable ID                                        GO_triticum
0  TraesCS4A02G403700                                                NaN
1  TraesCS3A02G154800  Catalysis of the reaction: acyl-CoA + H2O = Co...
2  TraesCS2B02G516800  Catalysis of the hydrolysis of any O-glycosyl ...
3  TraesCS2B02G516800  The chemical reactions and pathways involving ...
4  TraesCS2B02G516800  Catalysis of the hydrolysis of various bonds, ...

In [28]:
df_merged_mirna_gene_taes = pd.merge(df_merged_mirna_gene,df_taes,left_on='gene',right_on='Gene stable ID', how='left')
df_merged_mirna_gene_taes.head()

,miRNA_name,miRNA_l2fc,target,gene,gene_l2fc,Expectation,miRNA_aligned_fragment,Target_aligned_fragment,Inhibition,Gene stable ID,GO_triticum
0,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,TraesCS5B02G062100,Interacting selectively and non-covalently wit...
1,Cluster_9839,-1.373090,TraesCS2B02G490400.1,TraesCS2B02G490400,1.957450,2.5,AGGCGGUUACCUUGGCUAGC,GCUGGCCAAGGUGGCCGCCG,Cleavage,TraesCS2B02G490400,"Binds to and stops, prevents or reduces the ac..."
2,Cluster_9839,-1.373090,TraesCS2B02G490400.1,TraesCS2B02G490400,1.957450,2.5,AGGCGGUUACCUUGGCUAGC,GCUGGCCAAGGUGGCCGCCG,Cleavage,TraesCS2B02G490400,"Stops, prevents or reduces the activity of any..."
3,Cluster_9839,-1.373090,TraesCS2B02G490400.1,TraesCS2B02G490400,1.957450,2.5,AGGCGGUUACCUUGGCUAGC,GCUGGCCAAGGUGGCCGCCG,Cleavage,TraesCS2B02G490400,The cell membranes and intracellular regions i...
4,Cluster_10532,0.747036,TraesCS7A02G231200.1,TraesCS7A02G231200,-1.495536,3.0,UGGACGAGGAUGUGCAGCUGC,GCAGCUGCAGAUCCUCGUCGA,Cleavage,TraesCS7A02G231200,The component of a membrane consisting of the ...

In [29]:
df_merged_mirna_gene_taes.drop('Gene stable ID', axis=1, inplace=True)

In [30]:
df_merged_mirna_gene_taes.to_csv(path_merged,index=None)

### add other species genes

In [138]:
df_cross = pd.read_csv('../../data/GO/taes_aet_ath.csv',sep='\t')
print(len(df_cross.index))
df_cross.head(3)

194924

,Gene stable ID,Aegilops tauschii gene stable ID,Arabidopsis thaliana gene stable ID
0,TraesCS4A02G403700,AET6Gv20526800,NaN
1,TraesCS3A02G154800,NaN,NaN
2,TraesCS2B02G516800,AET2Gv21077700,NaN

In [139]:
#merge df
df_merged = pd.merge(df_target, df_cross, left_on='gene', right_on='Gene stable ID', how='left')
print(len(df_merged.index))
df_merged.head(3)

1198

,miRNA_name,target,Expectation,miRNA_aligned_fragment,Target_aligned_fragment,Inhibition,gene,Gene stable ID,Aegilops tauschii gene stable ID,Arabidopsis thaliana gene stable ID
0,Cluster_30749,TraesCS5B02G062100.1,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,TraesCS5B02G062100,TraesCS5B02G062100,AET5Gv20160400,AT4G02710
1,Cluster_30749,TraesCS5B02G062100.1,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,TraesCS5B02G062100,TraesCS5B02G062100,AET5Gv20160400,AT1G03080
2,Cluster_30749,TraesCS5B02G062100.1,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,TraesCS5B02G062100,TraesCS5B02G062100,AET5Gv20160400,AT3G22790

In [140]:
#remove Gene stable ID
df_merged.drop('Gene stable ID', axis=1, inplace=True)

In [141]:
df_merged.rename(columns={'Aegilops tauschii gene stable ID':'tauschii', 'Arabidopsis thaliana gene stable ID':'thaliana'}, inplace=True)

### tauschii

In [182]:
df_aet = pd.read_csv(path_aet,sep='\t')
df_aet = df_aet[['Gene stable ID','GO term name','GO domain']]
df_aet.rename(columns={'GO term name':'GO_term_tauschii','GO domain':'GO_domain_tauschii'}, inplace=True)
df_aet.head(5)

,Gene stable ID,GO_term_tauschii,GO_domain_tauschii
0,AET4Gv20696400,oxidation-reduction process,biological_process
1,AET4Gv20696400,glycerol-3-phosphate metabolic process,biological_process
2,AET4Gv20696400,glycerol-3-phosphate dehydrogenase complex,cellular_component
3,AET4Gv20696400,NAD binding,molecular_function
4,AET4Gv20696400,"oxidoreductase activity, acting on the CH-OH g...",molecular_function

In [183]:
df_merged_mirna_gene_taes_aet = pd.merge(df_merged_mirna_gene_taes,df_aet,left_on='tauschii',right_on='Gene stable ID', how='left')
df_merged_mirna_gene_taes_aet.head()

,miRNA_name,miRNA_l2fc,target,gene,gene_l2fc,Expectation,miRNA_aligned_fragment,Target_aligned_fragment,Inhibition,tauschii,thaliana,GO_term_triticum,GO_domain_triticum,Gene stable ID,GO_term_tauschii,GO_domain_tauschii
0,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,AET5Gv20160400,AT4G02710,actin binding,molecular_function,AET5Gv20160400,actin binding,molecular_function
1,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,AET5Gv20160400,AT4G02710,actin binding,molecular_function,AET5Gv20160400,actin binding,molecular_function
2,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,AET5Gv20160400,AT4G02710,actin binding,molecular_function,AET5Gv20160400,actin binding,molecular_function
3,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,AET5Gv20160400,AT4G02710,actin binding,molecular_function,AET5Gv20160400,NaN,NaN
4,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,AET5Gv20160400,AT4G02710,actin binding,molecular_function,AET5Gv20160400,actin binding,molecular_function

In [184]:
df_merged_mirna_gene_taes_aet.drop('Gene stable ID', axis=1, inplace=True)

In [188]:
df_merged_mirna_gene_taes_aet.head()

,miRNA_name,miRNA_l2fc,target,gene,gene_l2fc,Expectation,miRNA_aligned_fragment,Target_aligned_fragment,Inhibition,tauschii,thaliana,GO_term_triticum,GO_domain_triticum,GO_term_tauschii,GO_domain_tauschii
0,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,AET5Gv20160400,AT4G02710,actin binding,molecular_function,actin binding,molecular_function
1,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,AET5Gv20160400,AT4G02710,actin binding,molecular_function,actin binding,molecular_function
2,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,AET5Gv20160400,AT4G02710,actin binding,molecular_function,actin binding,molecular_function
3,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,AET5Gv20160400,AT4G02710,actin binding,molecular_function,NaN,NaN
4,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,AET5Gv20160400,AT4G02710,actin binding,molecular_function,actin binding,molecular_function

### thaliana

In [185]:
df_ath = pd.read_csv(path_ath,sep='\t')
df_ath = df_ath[['Gene stable ID','GO term name','GO domain']]
df_ath.rename(columns={'GO term name':'GO_term_arabidopsis','GO domain':'GO_domain_arabidopsis'}, inplace=True)
df_ath.head(5)

  Gene stable ID GO_term_arabidopsis GO_domain_arabidopsis
0      AT3G11415                 NaN                   NaN
1      AT1G31258                 NaN                   NaN
2      AT5G24735                 NaN                   NaN
3      AT2G45780                 NaN                   NaN
4      AT2G42425                 NaN                   NaN

In [186]:
df_merged_mirna_gene_taes_aet_ath = pd.merge(df_merged_mirna_gene_taes_aet,df_ath,left_on='thaliana',right_on='Gene stable ID', how='left')
df_merged_mirna_gene_taes_aet_ath.head()

,miRNA_name,miRNA_l2fc,target,gene,gene_l2fc,Expectation,miRNA_aligned_fragment,Target_aligned_fragment,Inhibition,tauschii,thaliana,GO_term_triticum,GO_domain_triticum,GO_term_tauschii,GO_domain_tauschii,Gene stable ID,GO_term_arabidopsis,GO_domain_arabidopsis
0,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,AET5Gv20160400,AT4G02710,actin binding,molecular_function,actin binding,molecular_function,AT4G02710,plasma membrane,cellular_component
1,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,AET5Gv20160400,AT4G02710,actin binding,molecular_function,actin binding,molecular_function,AT4G02710,actin binding,molecular_function
2,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,AET5Gv20160400,AT4G02710,actin binding,molecular_function,actin binding,molecular_function,AT4G02710,plasma membrane,cellular_component
3,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,AET5Gv20160400,AT4G02710,actin binding,molecular_function,actin binding,molecular_function,AT4G02710,actin filament binding,molecular_function
4,Cluster_30749,0.604528,TraesCS5B02G062100.1,TraesCS5B02G062100,1.378806,2.5,GCGGCUCUGUGGUGUUCAAGC,UGGUGACCACCACGGAGCCGC,Cleavage,AET5Gv20160400,AT4G02710,actin binding,molecular_function,actin binding,molecular_function,AT4G02710,plasma membrane,cellular_component