In [27]:
import pandas as pd
path_data_dir = "../../data/ss/04_02_19/"
path_res_dir = "../../data/res/04_02_19/"
path_deg_file = path_res_dir + "diffexpr-results.0.1.csv"

In [15]:
path_results = path_data_dir + "Results.txt"
df_res = pd.read_csv(path_results, sep="\t")
df_res.head(2)

,#Locus,Name,Length,Reads,RPM,UniqueReads,FracTop,Strand,MajorRNA,MajorRNAReads,...,DicerCall,MIRNA,PhaseScore,Short,Long,20,21,22,23,24
0,1A:209-460,Cluster_1,252,124,0.973,64,1.0,+,CGCGGAUUGCUCGAGCUGCUCACGCGGCGAGAGCGGGUCG,25,...,N,N2,-1.0,29,79,2,1,4,5,4
1,1A:688-753,Cluster_2,66,86,0.675,0,1.0,+,UAGACCGACUUUGUGAAAUG,5,...,N,N2,-1.0,8,56,7,1,3,6,5

In [16]:
df_res = df_res[df_res.MIRNA == "Y"]
print(len(df_res.index))

139

In [17]:
df_res.to_csv(path_data_dir + "results.valid.csv", sep="\t", index=None)

In [23]:
df_deg = pd.read_csv(path_deg_file, sep=",")
df_deg.head(2)

,Gene,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,X21dpiR1C.trimmed,X21dpiR3C.trimmed,X21dpiR1T.trimmed,X21dpiR3T.trimmed
0,Cluster_9839,305.159456,-1.373090,0.302426,-4.540247,0.000006,0.000494,418.738623,461.330424,144.769222,195.799555
1,Cluster_10532,4303.774066,0.747036,0.203659,3.668079,0.000244,0.010753,2874.998105,3552.828227,5197.787611,5589.482322

In [24]:
df_deg = df_deg[['Gene','log2FoldChange']]

In [25]:
df_deg_y = pd.merge(df_res, df_deg, left_on='Name', right_on='Gene')
df_deg_y.head(2)

,#Locus,Name,Length,Reads,RPM,UniqueReads,FracTop,Strand,MajorRNA,MajorRNAReads,...,PhaseScore,Short,Long,20,21,22,23,24,Gene,log2FoldChange
0,2A:652328872-652329011,Cluster_6291,140,1185,9.300,1,0.001,-,UGCCAAAGGAGAGUUGCCCUG,1136,...,-1.0,14,0,3,1155,11,2,0,Cluster_6291,-1.193250
1,2A:707747484-707747579,Cluster_6500,96,1395,10.948,1,0.999,+,UGGACGAGGAUGUGCAGCUGC,1119,...,-1.0,7,2,0,1385,1,0,0,Cluster_6500,0.832313

In [28]:
df_deg_y.to_csv(path_res_dir + "DEG.Y.csv", sep="\t", index=None)